DDNS.Web/Controllers/ConsoleController.cs
using DDNS.Provider.LoginLog;
using DDNS.Provider.Users;
using DDNS.ViewModel.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DDNS.Web.Controllers
{
    [Authorize]
    public class ConsoleController : Controller
    {
        private readonly UsersProvider _usersProvider;
        private readonly LoginLogProvider _loginLogProvider;

        public ConsoleController(UsersProvider usersProvider, LoginLogProvider loginLogProvider)
        {
            _usersProvider = usersProvider;
            _loginLogProvider = loginLogProvider;
        }

        /// <summary>
        /// 框架页面
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.User.FindFirst(u => u.Type == ClaimTypes.NameIdentifier).Value;
            var user = await _usersProvider.GetUserInfo(Convert.ToInt32(userId));

            return View(user);
        }

        /// <summary>
        /// 默认显示页面
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Home()
        {
            var userId = HttpContext.User.FindFirst(u => u.Type == ClaimTypes.NameIdentifier).Value;
            var user = await _usersProvider.GetUserInfo(Convert.ToInt32(userId));

            var log = await _loginLogProvider.GetLastLoginLog(Convert.ToInt32(userId));

            var info = new UserInfoViewModel
            {
                UserName = user.UserName,
                Email = user.Email,
                RegisterTime = user.RegisterTime,
                LastLoginTime = log.LoginTime,
                LastLoginIP = log.LoginIp
            };

            return View(info);
        }
    }
}

DDNS.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DDNS.Web.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

DDNS.Web/Controllers/TunnelController.cs
using DDNS.Entity.AppSettings;
using DDNS.Provider.Tunnel;
using DDNS.Provider.Users;
using DDNS.Web.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;

namespace DDNS.Web.Controllers
{
    [Authorize]
    public class TunnelController : Controller
    {
        private readonly UsersProvider _usersProvider;
        private readonly TunnelProvider _tunnelProvider;
        private readonly TunnelConfig _tunnelConfig;

        public TunnelController(UsersProvider usersProvider, TunnelProvider tunnelProvider, IOptions<TunnelConfig> config)
        {
            _usersProvider = usersProvider;
            _tunnelProvider = tunnelProvider;
            _tunnelConfig = config.Value;
        }

        /// <summary>
        /// 隧道列表
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 开通隧道
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            ViewData["Domain"] = _tunnelConfig.Domain;

            return View();
        }

        /// <summary>
        /// 开通隧道，指定用户
        /// </summary>
        /// <returns></returns>
        [PermissionFilter]
        public async Task<IActionResult> AdminCreate(int userId)
        {
            var user = await _usersProvider.GetUserInfo(userId);

            ViewData["Domain"] = _tunnelConfig.Domain;

            return View(user);
        }

        /// <summary>
        /// 审核申请隧道
        /// </summary>
        /// <returns></returns>
        [PermissionFilter]
        public IActionResult Audit()
        {
            return View();
        }

        /// <summary>
        /// 申请隧道详情
        /// </summary>
        /// <param name="tunnelId"></param>
        /// <returns></returns>
        [PermissionFilter]
        public async Task<IActionResult> AuditDetail(string tunnelId)
        {
            var tunnel = await _tunnelProvider.GetTunnel(tunnelId);

            return View(tunnel);
        }

        /// <summary>
        /// 隧道列表
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        [PermissionFilter]
        [HttpGet]
        public IActionResult List(int userId)
        {
            ViewData["UserId"] = userId;

            return View();
        }
    }
}

DDNS.Web/Controllers/UsersController.cs
using DDNS.Provider.Users;
using DDNS.Web.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DDNS.Web.Controllers
{
    [Authorize]
    [PermissionFilter]
    public class UsersController : Controller
    {
        private readonly UsersProvider _usersProvider;

        public UsersController(UsersProvider usersProvider)
        {
            _usersProvider = usersProvider;
        }

        /// <summary>
        /// 用户列表
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 添加用户
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _usersProvider.GetUserInfo(id ?? 0);

            return View(user);
        }
    }
}

DDNS.Web/Views/Console/Home.cshtml
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">@_localizer["title"]</div>
                <div class="layui-card-body">
                    <div class="layui-form">
                        <div class="layui-form-item">
                            <label class="layui-form-label">@_localizer["username"]：</label>
                            <div class="layui-form-mid">@Model.UserName</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">@_localizer["email"]：</label>
                            <div class="layui-form-mid">@Model.Email</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">@_localizer["registertime"]：</label>
                            <div class="layui-form-mid">@Model.RegisterTime</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">@_localizer["lastlogintime"]：</label>
                            <div class="layui-form-mid">@Model.LastLoginTime</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">@_localizer["lastloginip"]：</label>
                            <div class="layui-form-mid">@Model.LastLoginIP</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/js/jquery.min.js"></script>
    <script>
        $(".layui-form-label").css({
            "width": "100px",
            "font-weight":"bold"
        });
    </script>
}

DDNS.Web/Views/Console/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@_localizer["title"]</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="~/layuiadmin/layui/css/layui.css" rel="stylesheet" />
    <link href="~/layuiadmin/style/admin.css" rel="stylesheet" />
</head>
<body class="layui-layout-body">
    <div id="LAY_app">
        <div class="layui-layout layui-layout-admin">
            <div class="layui-header">
                <ul class="layui-nav layui-layout-left">
                    <li class="layui-nav-item layadmin-flexible" lay-unselect>
                        <a href="javascript:;" layadmin-event="flexible" title="@_localizer["flexible"]">
                            <i class="layui-icon layui-icon-shrink-right" id="LAY_app_flexible"></i>
                        </a>
                    </li>
                    <li class="layui-nav-item layui-hide-xs" lay-unselect>
                        <a href="@Url.Action("Index", "Home")" target="_blank" title="@_localizer["homepage"]">
                            <i class="layui-icon layui-icon-website"></i>
                        </a>
                    </li>
                    <li class="layui-nav-item" lay-unselect>
                        <a href="javascript:;" layadmin-event="refresh" title="@_localizer["refresh"]">
                            <i class="layui-icon layui-icon-refresh-3"></i>
                        </a>
                    </li>
                    <li class="layui-nav-item layui-hide-xs" lay-unselect>
                        <a href="javascript:;" layadmin-event="theme">
                            <i class="layui-icon layui-icon-theme"></i>
                        </a>
                    </li>
                    <li class="layui-nav-item layui-hide-xs" lay-unselect>
                        <a href="javascript:;" layadmin-event="fullscreen">
                            <i class="layui-icon layui-icon-screen-full"></i>
                        </a>
                    </li>
                </ul>
                <ul class="layui-nav layui-layout-right" lay-filter="layadmin-layout-right">
                    <li class="layui-nav-item" lay-unselect>
                        <a href="javascript:;">
                            <cite>@User.Identity.Name</cite>
                        </a>
                        <dl class="layui-nav-child">
                            <dd><a lay-href="@Url.Action("Home", "Console")">@_localizer["myinfo"]</a></dd>
                            <dd><a lay-href="@Url.Action("Password", "Account")">@_localizer["password"]</a></dd>
                            <dd><a href="@Url.Action("Logout", "Account")">@_localizer["logout"]</a></dd>
                        </dl>
                    </li>
                </ul>
            </div>
            <div class="layui-side layui-side-menu">
                <div class="layui-side-scroll">
                    <div class="layui-logo" lay-href="@Url.Action("Home", "Console")">
                        <span>@_localizer["pro"]</span>
                    </div>
                    <ul class="layui-nav layui-nav-tree" lay-shrink="all" id="LAY-system-side-menu" lay-filter="layadmin-system-side-menu">
                        <li data-name="home" class="layui-nav-item layui-nav-itemed">
                            <a href="javascript:;" lay-tips="@_localizer["home"]" lay-direction="2">
                                <i class="layui-icon layui-icon-home"></i>
                                <cite>@_localizer["home"]</cite>
                            </a>
                            <dl class="layui-nav-child">
                                <dd class="layui-this">
                                    <a lay-href="@Url.Action("Home", "Console")">@_localizer["myinfo"]</a>
                                </dd>
                            </dl>
                        </li>
                        @{
                            if (Model.IsAdmin == 1)
                            {
                                <li data-name="user" class="layui-nav-item">
                                    <a href="javascript:;" lay-tips="@_localizer["user"]" lay-direction="2">
                                        <i class="layui-icon layui-icon-user"></i>
                                        <cite>@_localizer["user"]</cite>
                                        <span class="layui-nav-more"></span>
                                    </a>
                                    <dl class="layui-nav-child">
                                        <dd><a lay-href="@Url.Action("Index", "Users")">@_localizer["users"]</a></dd>
                                        <dd><a lay-href="@Url.Action("Create", "Users")">@_localizer["createuser"]</a></dd>
                                    </dl>
                                </li>
                            }
                        }
                        <li data-name="tunnel" class="layui-nav-item">
                            <a href="javascript:;" lay-tips="@_localizer["tunnel"]" lay-direction="2">
                                <i class="layui-icon layui-icon-senior"></i>
                                <cite>@_localizer["tunnel"]</cite>
                                <span class="layui-nav-more"></span>
                            </a>
                            <dl class="layui-nav-child">
                                @{
                                    if (Model.IsAdmin == 1)
                                    {
                                        <dd><a lay-href="@Url.Action("Audit", "Tunnel")">@_localizer["audittunnel"]</a></dd>
                                    }
                                    else
                                    {
                                        <dd><a lay-href="@Url.Action("Index", "Tunnel")">@_localizer["tunnels"]</a></dd>
                                        <dd><a lay-href="@Url.Action("Create", "Tunnel")">@_localizer["createtunnel"]</a></dd>
                                    }
                                }
                            </dl>
                        </li>
                        <li data-name="set" class="layui-nav-item">
                            <a href="javascript:;" lay-tips="@_localizer["setting"]" lay-direction="2">
                                <i class="layui-icon layui-icon-set"></i>
                                <cite>@_localizer["setting"]</cite>
                            </a>
                            <dl class="layui-nav-child">
                                <dd>
                                    <a lay-href="@Url.Action("Password", "Account")">@_localizer["password"]</a>
                                </dd>
                            </dl>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="layadmin-pagetabs" id="LAY_app_tabs">
                <div class="layui-icon layadmin-tabs-control layui-icon-prev" layadmin-event="leftPage"></div>
                <div class="layui-icon layadmin-tabs-control layui-icon-next" layadmin-event="rightPage"></div>
                <div class="layui-icon layadmin-tabs-control layui-icon-down">
                    <ul class="layui-nav layadmin-tabs-select" lay-filter="layadmin-pagetabs-nav">
                        <li class="layui-nav-item" lay-unselect>
                            <a href="javascript:;"></a>
                            <dl class="layui-nav-child layui-anim-fadein">
                                <dd layadmin-event="closeThisTabs"><a href="javascript:;">@_localizer["tabsevent1"]</a></dd>
                                <dd layadmin-event="closeOtherTabs"><a href="javascript:;">@_localizer["tabsevent2"]</a></dd>
                                <dd layadmin-event="closeAllTabs"><a href="javascript:;">@_localizer["tabsevent3"]</a></dd>
                            </dl>
                        </li>
                    </ul>
                </div>
                <div class="layui-tab" lay-unauto lay-allowClose="true" lay-filter="layadmin-layout-tabs">
                    <ul class="layui-tab-title" id="LAY_app_tabsheader">
                        <li lay-id="@Url.Action("Home", "Console")" lay-attr="@Url.Action("Home", "Console")" class="layui-this"><i class="layui-icon layui-icon-home"></i></li>
                    </ul>
                </div>
            </div>
            <div class="layui-body" id="LAY_app_body">
                <div class="layadmin-tabsbody-item layui-show">
                    <iframe src="@Url.Action("Home", "Console")" frameborder="0" class="layadmin-iframe"></iframe>
                </div>
            </div>
            <div class="layadmin-body-shade" layadmin-event="shade"></div>
        </div>
    </div>
    <script src="~/layuiadmin/layui/layui.js"></script>
    <script>
        layui.config({
            base: '../layuiadmin/'
        }).extend({
            index: 'lib/index'
        }).use('index');
    </script>
</body>
</html>